### ISSUE TITLE
LUA Errors

### ISSUE THREAD

**Issue by Schrammo-star** [dernPerkins/DynamicCam-Classic#1]
Hey guy,

it's me! Schrammo-star!
I get LUA Errors :(

Here are 4 that I get the second I log in.

> Message: [string "for k,v in pairs(this.buffs) do ..."]:2: Usage: UnitBuff("unit", [index][, "filter"])
Time: Mon Sep 23 22:08:20 2019
Count: 1
Stack: [string "for k,v in pairs(this.buffs) do ..."]:2: Usage: UnitBuff("unit", [index][, "filter"])
[C]: in function `UnitBuff'
[string "for k,v in pairs(this.buffs) do ..."]:2: in main chunk
(tail call): ?
Interface\AddOns\DynamicCam\Core.lua:757: in function `?'
...AddOns\DynamicCam\Libs\AceTimer-3.0\AceTimer-3.0.lua:55: in function <...AddOns\DynamicCam\Libs\AceTimer-3.0\AceTimer-3.0.lua:50>
Locals: (*temporary) = "player"

> Message: ...AddOns\DynamicCam\Libs\AceEvent-3.0\AceEvent-3.0.lua:33: Attempt to register unknown event "ENCOUNTER_STOP"
Time: Mon Sep 23 22:08:20 2019
Count: 1
Stack: ...AddOns\DynamicCam\Libs\AceEvent-3.0\AceEvent-3.0.lua:33: Attempt to register unknown event "ENCOUNTER_STOP"
[C]: in function `RegisterEvent'
...AddOns\DynamicCam\Libs\AceEvent-3.0\AceEvent-3.0.lua:33: in function `OnUsed'
...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:142: in function `RegisterEvent'
Interface\AddOns\DynamicCam\Core.lua:1428: in function `RegisterSituationEvents'
Interface\AddOns\DynamicCam\Core.lua:1418: in function `?'
...AddOns\DynamicCam\Libs\AceTimer-3.0\AceTimer-3.0.lua:55: in function <...AddOns\DynamicCam\Libs\AceTimer-3.0\AceTimer-3.0.lua:50>
Locals: (*temporary) = AceEvent30Frame {
 0 = <userdata>
}
(*temporary) = "ENCOUNTER_STOP"

> Message: ...AddOns\DynamicCam\Libs\AceEvent-3.0\AceEvent-3.0.lua:33: Attempt to register unknown event "SHIPMENT_CRAFTER_OPENED"
Time: Mon Sep 23 22:08:20 2019
Count: 1
Stack: ...AddOns\DynamicCam\Libs\AceEvent-3.0\AceEvent-3.0.lua:33: Attempt to register unknown event "SHIPMENT_CRAFTER_OPENED"
[C]: in function `RegisterEvent'
...AddOns\DynamicCam\Libs\AceEvent-3.0\AceEvent-3.0.lua:33: in function `OnUsed'
...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:142: in function `RegisterEvent'
Interface\AddOns\DynamicCam\Core.lua:1428: in function `RegisterSituationEvents'
Interface\AddOns\DynamicCam\Core.lua:1418: in function `?'
...AddOns\DynamicCam\Libs\AceTimer-3.0\AceTimer-3.0.lua:55: in function <...AddOns\DynamicCam\Libs\AceTimer-3.0\AceTimer-3.0.lua:50>
Locals: (*temporary) = AceEvent30Frame {
 0 = <userdata>
}
(*temporary) = "SHIPMENT_CRAFTER_OPENED"

> Message: [string "for k,v in pairs(this.buffs) do ..."]:2: Usage: UnitBuff("unit", [index][, "filter"])
Time: Mon Sep 23 22:10:20 2019
Count: 14
Stack: [string "for k,v in pairs(this.buffs) do ..."]:2: Usage: UnitBuff("unit", [index][, "filter"])
[C]: in function `UnitBuff'
[string "for k,v in pairs(this.buffs) do ..."]:2: in main chunk
(tail call): ?
Interface\AddOns\DynamicCam\Core.lua:757: in function `EvaluateSituations'
Interface\AddOns\DynamicCam\Core.lua:1402: in function `?'
...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119: in function <...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:29: in function <...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: in function `Fire'
...AddOns\DynamicCam\Libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...AddOns\DynamicCam\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>
Locals: <none>

Can you help me fix those? :)

**Comment by dernPerkins** [comment]
For the message about "ENCOUNTER_STOP" supposedly that was a known bug and is listed in the Options.lua 

> Pre-8.0 profiles may not have cleanly been upgraded and can throw errors (ENCOUNTER_STOP)

I'll be taking a look at all your errors as soon as I can though. Thanks for posting :D

**Comment by dernPerkins** [comment]
When looking into this I'm guessing the errors are coming from using a profile that is associated with features of 8.1. Probably the default profile that comes with the addon. Could you please @Schrammo-star, give me some more info on how you setup the addon, maybe the profile that you're using, whether it be a default one or an old one. Thank you

**Comment by dernPerkins** [comment]
I'm closing this bug for now unless further information on reproduction of the bugs are given.
