### ISSUE TITLE
Package zip with DynamicCam-Classic folder

### ISSUE THREAD

**Issue by MarkPflug** [dernPerkins/DynamicCam-Classic#2]
It took me a while to figure out that I needed to unzip the addon into a "DynamicCam-Classic" folder. It would be nice if the zip file had all of the files in such a folder instead of in the root path.

**Comment by dernPerkins** [comment]
Newest release and releases to follow will now in the proper structure like other addons have typically had it. My mistake, should've realized that was wrong when I created it in the first place.
