### ISSUE TITLE
Invalid spell IDs in "annoying spells" scenario cause it to trigger on all UNIT_AURA events

### ISSUE THREAD

**Issue by Flaimb0t** [dernPerkins/DynamicCam-Classic#3]
Currently the "Annoying Spells" scenario contains the following spell IDs by default:
46924, 51690, 188499, 210152
These are not implemented in classic, which triggers the scenario on UNIT_AURA events.

Precondition:
* Annoying spells scenario is enabled
* Annoying spells scenario is currently not active
* Invalid ID is present in the executeOnInit buff list

Replication:
* Be warrior 
* use Bloodrage

Expected behaviour:
* Annoying spells scenario does NOT activate

Observed behaviour:
* Annoying spells scenario is activated and engaged

Quick workaround:
* remove invalid IDs from the annoying spell list

**Comment by LudiusMaximus** [comment]
Making your requested changes will be no problem. But maybe you can enlighten me first. Because I actually do not understand, what the "annoying spells" situation is meant for in the first place. Why do you have it activated anyway?

**Comment by Flaimb0t** [comment]
> Why do you have it activated anyway?  

That's the default setting, so i didn't touch it at first.

> Because I actually do not understand, what the "annoying spells" situation is meant for in the first place.  

Good question, as it doesn't seem to alter the camera behaviour in a drastic manner. I think it's just to have an option for specific spells to keep the overview. I've looked up the IDs and they're the following:
* https://www.wowhead.com/spell=46924/bladestorm
* https://www.wowhead.com/spell=210152/death-sweep
* https://www.wowhead.com/spell=188499/blade-dance
* https://www.wowhead.com/spell=51690/killing-spree

To me these seem like good candidates to zoom out a lot to not lose track of your position and surroundings due to them making your character behave...awkardly. Maybe Mpstark can enlighten us about his intentions behind this scenario.

**Comment by LudiusMaximus** [comment]
I asked him on Discord, waiting for an answer. For the time being, you should disable all situations you are not actively using.

Furthermore, this project here is not maintained any more. We now have a classic branch over at https://github.com/Mpstark/DynamicCam and you can get the releases at: https://www.curseforge.com/wow/addons/dynamiccam

**Comment by LudiusMaximus** [comment]
All right. So apparently "annoying spells" is meant to make exclusions from your default settings. E.g. when you have some action cam settings in your defaults that you want to disable while certain spells are active. Anyway, I will fix the issue with unknown spells in the next classic release at https://www.curseforge.com/wow/addons/dynamiccam.
